## Упражнения по библиотеке Numpy

In [91]:
import numpy as np

np.random.seed(21)

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [23]:
array = np.random.randint(0, 11, size=10)
print(array)
array = np.where((array > 3) & (array < 8), -array, array)
print(array)

[0 9 7 5 2 7 5 0 4 2]
[ 0  9 -7 -5  2 -7 -5  0 -4  2]


**2.** Заменить максимальный элемент случайного массива на 0

In [27]:
array = np.random.randint(1, 11, size=10)
print(array)
array[array == np.max(array)] = 0
print(array)

[ 2  4  7  9  2 10  2  1 10  9]
[2 4 7 9 2 0 2 1 0 9]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
array = [[0, 2, 4],
         [1, 3, 5]]
print(array)

# Генерируем сетку координат
# indexing='ij' гарантирует правильный порядок при переборе
grid = np.meshgrid(*array, indexing='ij')

# Объединяем сетки в один массив комбинаций
# stack склеивает массивы, а reshape(-1, N) вытягивает их в список пар
result_array = np.stack(grid, axis=-1).reshape(-1, len(array))

print(result_array)

[[0, 2, 4], [1, 3, 5]]
[[0 1]
 [0 3]
 [0 5]
 [2 1]
 [2 3]
 [2 5]
 [4 1]
 [4 3]
 [4 5]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [28]:
array_a = np.random.randint(0, 10, (8, 3))
array_b = np.array([
    [1, 2],
    [3, 4]
])
print(f"A:\n{array_a}")
print(f"B:\n{array_b}")

# 1. Где в A есть числа из первой строки B?
mask1 = np.isin(array_a, array_b[0]).any(axis=1)

# 2. Где в A есть числа из второй строки B?
mask2 = np.isin(array_a, array_b[1]).any(axis=1)

# 3. Итоговая маска (И то, и другое)
final_mask = mask1 & mask2

# Для индексов строк
indices = np.where(final_mask)[0]

# Итоговая маска
result_rows = array_a[final_mask]

print("Result:")
if indices.size > 0:
    for idx in indices:
        print(f"Row №{idx}: {array_a[idx]}")
else:
    print("No rows found")

A:
[[3 9 4]
 [0 2 9]
 [0 8 1]
 [1 4 6]
 [8 5 0]
 [3 5 7]
 [0 8 5]
 [3 7 7]]
B:
[[1 2]
 [3 4]]
Result:
Row №3: [1 4 6]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [7]:
matrix = np.random.randint(0, 3, (10, 3))
print(matrix)

# Вычисляем размах для каждой строки
# axis=1 означает, что мы ищем max и min внутри каждой строки
# np.ptp (Peak-to-Peak) вычисляет разницу max - min.
# Если она равна 0, значит все числа в строке идентичны.
ranges = np.ptp(matrix, axis=1)

# Создаем маску: оставляем только те строки, где размах больше 0
mask = ranges > 0

result = matrix[mask]
print(f"Result:\n{result}")

[[1 1 1]
 [2 0 0]
 [2 2 0]
 [2 1 0]
 [2 2 2]
 [0 0 1]
 [1 2 2]
 [1 1 0]
 [2 2 2]
 [0 1 2]]
Result:
[[2 0 0]
 [2 2 0]
 [2 1 0]
 [0 0 1]
 [1 2 2]
 [1 1 0]
 [0 1 2]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [29]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],  # Дубликат
    [0, 0, 0],
    [7, 8, 9],
    [0, 0, 0],  # Дубликат
    [1, 2, 3]  # Еще один дубликат
])
print(matrix)

# np.unique удаляет дубликаты
# axis=0 - сравнение строк
# return_index - номера строк исходной матрицы, которые остались
unique_matrix = np.unique(matrix, axis=0, return_index=True)

print(f"Result:\n{unique_matrix}")

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [0 0 0]
 [7 8 9]
 [0 0 0]
 [1 2 3]]
Result:
(array([[0, 0, 0],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([3, 0, 1, 4]))


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [79]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

# --------- Numpy ---------
non_zero_elements = X.diagonal()[X.diagonal() != 0]

if non_zero_elements.size > 0:
    product = np.prod(non_zero_elements)
else:
    product = 0

print(f"Matrix:\n{X}")
print(f"Non zero elements: {non_zero_elements}")
print(f"Product: {product}")

# --------- Python ---------
import math
def py_non_zero_elements(arr: list) -> int:
    prod = 1
    elements = [row[i] for i, row in zip(range(len(arr[0])), arr) if row[i] != 0]
    if elements:
        prod *= math.prod(elements)
        return prod
    return -1

print(f"Py product: {py_non_zero_elements(X)}")

Matrix:
[[1 0 1]
 [2 0 2]
 [3 0 3]
 [4 4 4]]
Non zero elements: [1 3]
Product: 3
Py product: 3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [80]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

# --------- Numpy ---------

# Мультимножество - элементы и их количесво совпадают
# 1. Сортируем оба вектора
# 2. Сравниваем их поэлементно
# 3. Проверяем, что все элементы совпали
are_equal = np.array_equal(np.sort(x), np.sort(y))

print(f"Vector x: {x}")
print(f"Vector y: {y}")
print(f"Are equal? {are_equal}")

# --------- Python ---------

from collections import Counter

print(f"Py equal: {Counter(x) == Counter(y)}")

Vector x: [1 2 2 4]
Vector y: [4 2 1 2]
Are equal? True
Py equal: True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [81]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

# --------- Numpy ---------

# Получаем все элементы, стоящие после нулей
targets = x[1:][x[:-1] == 0]
print(f"Targets: {targets}")

if targets.size > 0:
    max_elem_after_zero = targets.max()
    print(f"Max element after 0: {max_elem_after_zero}")
else:
    print("No elements found")

# --------- Python ---------

py_targets = [curr for prev, curr in zip(x, x[1:]) if prev == 0]
if py_targets:
    print(f"Py max element after 0: {max(py_targets)}")


Targets: [3 0 5]
Max element after 0: 5
Py max element after 0: 5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [90]:
x = np.array([2, 2, 2, 3, 3, 3, 5])

# --------- Numpy ---------

# Находим индексы, где значения меняются
# Сравниваем соседние элементы: x[i] != x[i+1]
mask = x[1:] != x[:-1]

# Индексы изменений (добавляем индекс последнего элемента вручную)
indices = np.append(np.where(mask)[0], x.size - 1)

# Значения (первый вектор кортежа)
# Это просто элементы массива x в точках, где серия заканчивается
values = x[indices]

# Длины серий — это разность между индексами изменений
counts = np.diff(np.append(-1, indices))
print(f"Np: {values, counts}")

# --------- Python ---------

from itertools import groupby

def py_rle(x):
    py_values = []
    py_counts = []

    # groupby собирает идущие подряд одинаковые элементы
    # k - сам элемент, g - итератор группы этих элементов
    for k, g in groupby(x):
        py_values.append(int(k))
        # Суммируем единицы для каждого элемента в группе, чтобы получить длину
        py_counts.append(sum(1 for _ in g))

    return py_values, py_counts


print(f"Py: {py_rle(x)}")

Np: (array([2, 3, 5]), array([3, 3, 1]))
Py: ([2, 3, 5], [3, 3, 1])


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [53]:
from scipy.spatial.distance import cdist
import time
x = np.random.rand(1000, 30)
y = np.random.rand(1100, 30)

def np_dist(x, y):
    x_sq = np.sum(x**2, axis=1)[:, np.newaxis]
    y_sq = np.sum(y**2, axis=1)
    # Матричное умножение @
    return np.sqrt(np.maximum(x_sq + y_sq - 2 * x @ y.T, 0))

# Тайминг NumPy
start = time.time()
res_numpy = np_dist(x, y)
time_np = time.time() - start
print(f"Time np: {time_np}")

# Тайминг SciPy cdist
start = time.time()
res_scipy = cdist(x, y, metric='euclidean')
time_scipy = time.time() - start
print(f"Time SciPy: {time_scipy}")


Time np: 0.015062332153320312
Time SciPy: 0.01169443130493164


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [54]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [55]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [63]:
crunchie_munchies_calories = 60
average_calories = np.mean(calorie_stats)
average_calories_diff = average_calories- crunchie_munchies_calories
print(f"Average calories: {average_calories}")
print(f"Average calories difference: {average_calories_diff}")

Average calories: 106.88311688311688
Average calories difference: 46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [59]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [62]:
median_calories = np.median(calorie_stats_sorted)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [65]:
# Перебираем процентили от 1 до 100
for p in range(1, 101):
    current_percentile_value = np.percentile(calorie_stats, p)
    print(f"{p}th percentile: {current_percentile_value}")

    # Как только значение превысило 60, сохраняем и выходим из цикла
    if current_percentile_value > 60:
        nth_percentile = p
        break

# 4% Конкурентов имеют колорийность, равную нам или ниже
print(f"Final percentile: {nth_percentile}")

1th percentile: 50.0
2th percentile: 50.0
3th percentile: 55.599999999999994
4th percentile: 70.0
Final percentile: 4


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [73]:
more_calories = np.mean(calorie_stats > 60) * 100
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [75]:
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [22]:
#Выбирайте CrunchieMunchies! Мы гарантируем стабильные 60 калорий в каждой пачке!